# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-nodejs

name: Node.js CI

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  pull_request: {}
  push: {}
  schedule:
  # Run once a day (at 8:40 AM UTC) to check for exogenous breakage.
  # TODO: Run when dependencies are updated.  (Like Dependabot, but on
  # in-range updates and without sending a PR.)
  - cron: '40 8 * * *'

jobs:
  test-primary:
    name: Lint and Test on Node.js * x64 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        # '*' is "latest":
        # https://github.com/actions/setup-node/issues/61#issuecomment-577548687
        # https://github.com/actions/setup-node/issues/164#issuecomment-648999618
        # https://github.com/actions/setup-node/pull/104
        node-version: '*'
        architecture: x64
    - name: Display Node.js version
      run: node --version
    - name: Display npm version
      run: npm --version
    - name: Update npm
      run: npm install -g npm@^6
    - name: Install dependencies
      run: npm install --strict-peer-deps
    - name: Lint
      run: npm run lint
    - name: Run tests
      run: npm run test-unit
